;**
;**	SOUND.SH -- Global defines for all music and sound effects
;**
;**	LSL1:  Leisure Suit Larry in the Land of the Lounge Lizards
;**				Copyright 1987, 1991
;**				by Al Lowe
;**
;**	Programmed by Oliver Brelsford &
;**
;**	Last Update:  June 18, 1991
;**
;**
;**		Note:  Lines that begin with a semicolon (";") indicate sounds
;**	that are used in only one scene.
;**


;(define	sNuclearBlowup			101)		;**	100 Lefty's Exterior
(define	sDogPissing				102)		;**	reused in 130
;(define	mDog						103)		;**	used in sidewalk
;(define	mPoliceman				104)
;(define	sNuclearHiss			105)		;**	100 Lefty's Exterior

(define	mBarInterior			110)		;**	110 Lefty's Interior
(define	sDrinking				111)
;(define	sMugOnBar				112)
;(define	sBartenderSwoosh		113)
;(define	sPantsDown				114)
;(define	sPantsUp					115)
;(define	sRecordStart			116)
;(define	sRecordNoise			117)
;(define	sRecordDone				118)
;(define	sPeepholeSlider		119)

;(define sHicUp					121)

;(define	sDripping				130)		;**	130 	Bathroom
;(define	sWashHands				131)
;(define	sNewspaperShuffle		132)
(define	sFart						133)
;(define	sToiletFlush			134)
;(define	sToiletGusher			135)
;(define sDrip						136)

(define	sChannelChanging		140)		;**	140 	PimpRoom
;(define	mChannel1				141)		;**	Soap opera-Lush romantic
;(define	mChannel2				142)		;**	Tom Bidet for Motel-69
;(define	mChannel3				143)		;**	Software developer's
;(define	mChannel4				144)		;**	Wild Kingdom Rhino fight
;(define	mChannel5				145)		;**	Mr. Rogers theme
;(define	mChannel6				146)		;**	High power sports
;(define	mChannel7				147)		;**	Masterpiece Theater music, Handel
(define	mChannel8				148)		;**	Slow grooving porn funk

;(define	mHooker					150)		;**	150 	HookersRoom
;(define	sWindowUp				151)
;(define	sGumPopping				155)		;**	155 	HookerCloseup

;(define	sFalling					160)		;**	160 	TrashbinAlley
;(define	sLandInTrash			161)
;(define	sOutOfTrash				163)
;(define	sSplatOnPavement		164)
;(define	mTrapeze					165)
(define	sGlassBreaking			167)

;(define	mDarkAlley				170)		;**	170 	Dark Alley
(define	sFight					171)
;(define	mDizzy					172)

(define	mDeath					190)		;**	190 	Death
(define	sGroundOpens			191)
(define	sElevator				192)
;(define	sFactory					193)
;(define	sEgoOffElevator		194)
;(define	sBlender					195)
;(define	sGurgle					196)
;(define	sMachineGrunts			197)
;(define	sSquirt					198)
;(define	sConveyor				199)

;(define	sYellTaxi				200)		;**	200 	Taxi
;(define	sCabComing				201)
;(define	sCabTires				202)
;(define	sCabDoorOpen			203)
;(define	sCabDoorClose			204)
;(define	sCabDeparting			205)
(define	mCab						206)

;(define	sCardOn					250)		;**	250 	Blackjack
;(define	sBJlose					251)
;(define	sBJwin					252)
;(define sBlackJack				253)

(define	sButtonPress			260)		;**	260 	Slot machine
;(define	sWheelsSpinning		261)
;(define	sWheelStopping			262)
;(define	sWinSmall				263)
;(define	sWinBig					264)
;(define	sWinJackpot				265)
(define	sCashOut					266)

;(define	sDoorsCasino			300)		;**	300 	OutsideCasino
(define	sFountain				301)
;(define	mAppleMan				302)

(define	mCasino					310)		;**	310 	CasinoInterior
;(define	sGreedSqueals			311)
;(define	sConversation			312)

(define	mCanCan					320)		;**	320 	Cabaret
(define	sDrumFill1				321)
;(define	sDrumFill2				322)
;(define	sDrumFill3				323)
;(define	sDrumFill4				324)
;(define	sDrumFill5				325)
;(define	sDrumFill6				326)

													;**	330 	FirstFloor

(define	sElevatorFloorDing	340)		;**	340	GenericFloor
(define	sKnocking				341)

(define	sElevatorDoors			350)		;**	350 	EighthFloor
(define	mFloor8					351)
;(define	mPills					352)
;(define	mFaithLeaving			353)

(define	mFaith					355)		;**	355	Faith Closeup

													;**	360 	PentLivingRoom

;(define	sInflateDoll			370)		;**	370 	PentBedroom
;(define	sDollPops				371)
(define	sDollDeflating			372)
;(define	sFireworksLaunch		373)
;(define	sFireworksExplosions	374)

;(define	sBubbles					380)		;**	380 	PentHotTub
(define	mHotTub					381)
;(define	sCatCall					382)
;(define sSplash					384)

(define	mMacTheKnife			390)
;(define	sKnifeFlip				393)
;(define	sCuttingRibbon			394)
;(define	sCommercial				395)
;(define  mHoneyMoon2				396)

;(define	sFlasherOpening 		400)		;**	400 	QuikiwedExterior
;(define	sFlasherClosing 		401)

(define	mSyrupOrgan				410)		;**	410 	QuikiwedInt
(define	mLohingren				411)

;(define	mDrunk					120)		;**	120 	StoreRoom, now used in 500

;(define	sPhoneDialTone			490)		;**	500 	QuikiMartExterior
;(define	sPhone1					491)
;(define	sPhone2					492)
;(define	sPhone3					493)
;(define	sPhone4					494)
;(define	sPhone5					495)
;(define	sPhone6					496)
;(define	sPhone7					497)
;(define	sPhone8					498)
;(define	sPhone9					499)
;(define	sPhoneAsterisk			500)
;(define	sPhonePoundSign		501)
;(define	sPhoneBusy 				502)
;(define	sPhoneRinging 			503)
;(define	sPhoneRingingHere		504)
;(define	sPhoneAnswered			505)
;(define	sPhoneHangUp			506)
;(define	sPhoneHangUpHere		507)


(define	mQuikiMartInterior	510)		;**	510 	QuikiMartInterior
;(define	sHeadsOut				511)
;(define	sPervert					512)
;(define	sHeadsIn					513)
;(define	sGunshot					514)

;(define	mDiscoExterior			600)     ;**	600 	DiscoExterior

(define	mDiscoInterior			610)		;**	610 	DiscoInterior
;(define	mDanceNumber			611)

(define	mThemeSong				700)		;**	700 	Titles

;(define	sQuestionAppears		710)		;**	710	Trivia Quiz
;(define	sCorrect					711)
;(define	sWrong					712)

(define	sCitySounds				800)		;**	800 Misc
(define	sDoorOpen				801)
(define	sDoorClose				802)
;(define	sNeonBuzz				803)
(define	sCarHonk					810)
(define	sCarThump				811)
(define	sCarLeaving				812)
(define	sBreathSpray			820)
(define	sScoredPoints			821)
